# Generated by Django 2.2.2 on 2019-06-30 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='rating',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
