# Generated by Django 2.2.2 on 2019-07-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_auto_20190701_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='last_edited',
            field=models.DateField(null=True),
        ),
    ]
